name: Setup tools shared
description: Setup platform tools

inputs:
  platform:
    description: "Runner platform"
    required: true
  build_type:
    description: "Release or Debug"
    required: true

runs:
  using: "composite"

  steps:
    - shell: bash
      if: inputs.platform == 'ubuntu-latest'
      run: sudo apt-get update -q

    - uses: actions/setup-python@v4.5.0
      with: 
        python-version: "3.8"
        cache: "pip"

    - shell: bash
      run: pip install -r requirements.txt

    - name: Install conan config
      shell: bash
      run: conan config install https://github.com/JesusKrists/JEngine-conan-settings.git

    - uses: seanmiddleditch/gha-setup-ninja@v3

    - uses: jwlawson/actions-setup-cmake@v1.13.1

    - name: Setup VS Dev Environment - Windows
      if: inputs.platform == 'windows-latest'
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
      
    - name: Install SDL2 dependencies - Ubuntu
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: sudo apt-get install -y -q xorg-dev libudev-dev libts-dev libgl1-mesa-dev libegl-dev libegl1-mesa-dev
        && sudo apt-get install -y -q libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libxinerama-dev
        && sudo apt-get install -y -q libvorbis-dev libaudiofile-dev libfreetype6-dev libusb-dev libxrandr-dev
        && sudo apt-get install -y -q libdbus-1-dev zlib1g-dev libdirectfb-dev libgles-dev libibus-1.0-dev libx11-dev mesa-utils

    - name: Install Mesa3D - Windows
      if: inputs.platform == 'windows-latest'
      uses: ssciwr/setup-mesa-dist-win@v1
      with:
        version: "21.3.7"

    - name: Output glxinfo - Ubuntu
      uses: GabrielBB/xvfb-action@v1.6
      if: inputs.platform == 'ubuntu-latest'
      with:
        run: glxinfo