name: Setup tools shared
description: Setup platform tools

runs:
  using: 'composite'

  steps:
    - shell: bash
      if: runner.os == 'Linux'
      run: sudo apt-get update -q

    - uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.8'
        cache: 'pip'

    - shell: bash
      run: pip install -r requirements.txt

    - name: Install conan config
      shell: bash
      run: conan config install https://github.com/JesusKrists/JEngine-conan-settings.git

    - uses: seanmiddleditch/gha-setup-ninja@v3

    - uses: jwlawson/actions-setup-cmake@v1.13.1

    - name: Setup VS Dev Environment - Windows
      if: runner.os == 'Windows'
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Install SDL2 dependencies - Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -y -q xorg-dev libudev-dev libts-dev libgl1-mesa-dev libegl-dev libegl1-mesa-dev
        && sudo apt-get install -y -q libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libxinerama-dev
        && sudo apt-get install -y -q libvorbis-dev libaudiofile-dev libfreetype6-dev libusb-dev libxrandr-dev
        && sudo apt-get install -y -q libdbus-1-dev zlib1g-dev libdirectfb-dev libgles-dev libibus-1.0-dev mesa-utils
        && sudo apt-get install -y -q libx11-dev libx11-xcb-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev

    - name: Install Mesa3D - Windows
      if: runner.os == 'Windows'
      uses: ssciwr/setup-mesa-dist-win@v1
      with:
        version: '22.3.5'

    - name: Install wglinfo - Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: curl.exe -L --output wglinfo64.exe --url https://github.com/gkv311/wglinfo/releases/download/22_03/wglinfo64.exe

    - name: Output glxinfo - Ubuntu
      uses: GabrielBB/xvfb-action@v1.6
      if: runner.os == 'Linux'
      with:
        run: glxinfo

    - name: Output wglinfo - Windows
      if: runner.os == 'Windows'
      shell: cmd
      env:
        GALLIUM_DRIVER: llvmpipe
      run: wglinfo64
