name: Setup CI cache
description: Setup CI cache

runs:
  using: 'composite'

  steps:
    - name: Cache conan dependencies
      uses: actions/cache@v3.2.6
      with:
        path: |
          ~/.cpm
        key: ${{ hashfiles('package-lock.cmake') }}
